name: Test cucumber-core

on:
  push:

  schedule:
    - cron: "0 5 * * *"

  workflow_call:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: ['2.6', '2.7', '3.0', '3.1']

        include:
          - os: ubuntu-latest
            ruby: jruby

          - os: macos-latest
            ruby: '3.0'

          - os: windows-latest
            ruby: '3.0.6'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec cucumber
        shell: bash
